### Register a new donor
POST http://localhost:1234/donor/register
Content-Type: application/json

{
  "name": "Aarthi",
  "email": "aarthi@gmail.com",
  "password": "pass123",
  "phone": "1274674830",
  "location": "salem",
  "blood_group": "B+ve",
  "date_of_birth": "2005-02-24"
}

### Get all donors
GET http://localhost:1234/donor/all

### Donor Login (Test this after registering a donor)
POST http://localhost:1234/donor/login
Content-Type: application/json

{
  "email": "aarthi@gmail.com",
  "password": "pass123"
}

#####
POST http://localhost:1234/hospital/register
Content-Type: application/json

{
  "name": "KMC Hospital",
  "email": "kmchospital@gmail.com",
  "password": "Pass123",
  "phone": "9876543780",
  "location": "Salem",
  "registration_number": "HOSP456"
}

####
POST http://localhost:1234/hospital/login
Content-Type: application/json

{
  "email": "kmchospital@gmail.com",
  "password": "Pass123"
}

